version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6400:6379"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: antifraud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"

volumes:
  postgres_data:
